[tools]
# Languages
node = "24"
python = "3.12"
go = "1.22"

# CLI Tools (previously from Homebrew)
jq = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
hub = "latest"
peco = "latest"
starship = "latest"
vim = "latest"
heroku-cli = "latest"
license-plist = "latest"

# NPM Global Tools
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:firebase-tools" = "latest"
"npm:vercel" = "latest"
"npm:@vue/cli" = "latest"
"npm:next" = "latest"
"npm:wrangler" = "latest"
"npm:gitmoji-cli" = "latest"
"npm:ts-node" = "latest"
"npm:nodemon" = "latest"

# iOS Development
tuist = "4.55.6"

# Go workspace management
"npm:@shutootaki/gwm" = "latest"

[settings]
experimental = true
